function new = factor(p, Q, fl, t, pa)
%% FACTOR update new factor prices
% factor market clearing condition
%  find updated wage, and then recover the factor price_h
% we just change the p temporarily, we will store it as another variable in
% temp_e

X1 = Q.oL(:, 1, t) .* p.w_L(:, t).* Q.L(:, t) +  Q.oH(:, 1, t) .* p.w_H(:, t).* Q.H(:, t) ...
        + Q.oK(:, 1, t) .* p.r(:, t).*Q.k(:, t) ;
X2 = Q.oL(:, 2, t) .* p.w_L(:, t).* Q.L(:, t) +  Q.oH(:, 2, t) .* p.w_H(:, t).* Q.H(:, t) ...
        + Q.oK(:, 2, t) .* p.r(:, t).*Q.k(:, t) ;
X3 = Q.oL(:, 3, t) .* p.w_L(:, t).* Q.L(:, t) +  Q.oH(:, 3, t) .* p.w_H(:, t).* Q.H(:, t) ...
        + Q.oK(:, 3, t) .* p.r(:, t).*Q.k(:, t) ;
X4 = Q.oL(:, 4, t) .* p.w_L(:, t).* Q.L(:, t) +  Q.oH(:, 4, t) .* p.w_H(:, t).* Q.H(:, t) ...
        + Q.oK(:, 4, t) .* p.r(:, t).*Q.k(:, t) ;

if t ==1 
    new.w_Hh = ( pa.mu_H(1) * sum(fl.S1(:,:,t) .* repmat( X1, 1, pa.num ), 1 )'     ...
                    + pa.mu_H(2) * sum(fl.S2(:,:,t) .* repmat( X2, 1, pa.num ), 1 )'      ...
                    + pa.mu_H(3) * sum(fl.S3(:,:,t) .* repmat( X3, 1, pa.num ), 1 )'     ...
                    + pa.mu_H(4) * sum(fl.S4(:,:,t) .* repmat( X4, 1, pa.num ), 1 )'   ) ...
                    ./ ( p.w_H0 .* Q.H(:, t)   ); 
    new.w_Lh = ( pa.mu_L(1) * sum(fl.S1(:,:,t) .* repmat( X1, 1, pa.num ), 1 )'     ...
                    + pa.mu_L(2) * sum(fl.S2(:,:,t) .* repmat( X2, 1, pa.num ), 1 )'      ...
                    + pa.mu_L(3) * sum(fl.S3(:,:,t) .* repmat( X3, 1, pa.num ), 1 )'     ...
                    + pa.mu_L(4) * sum(fl.S4(:,:,t) .* repmat( X4, 1, pa.num ), 1 )'   ) ...
                    ./ ( p.w_L0 .* Q.L(:, t)   ); 
    new.r_h = ( pa.mu_K(1) * sum(fl.S1(:,:,t) .* repmat( X1, 1, pa.num ), 1 )'    ...
                    + pa.mu_K(2) * sum(fl.S2(:,:,t) .* repmat( X2, 1, pa.num ), 1 )'      ...
                    + pa.mu_K(3) * sum(fl.S3(:,:,t) .* repmat( X3, 1, pa.num ), 1 )'     ...
                    + pa.mu_K(4) * sum(fl.S4(:,:,t) .* repmat( X4, 1, pa.num ), 1 )'   ) ...
                    ./ ( p.r0 .* Q.k(:, t)   ); 
else
    new.w_Hh = ( pa.mu_H(1) * sum(fl.S1(:,:,t) .* repmat( X1, 1, pa.num ), 1 )'     ...
                    + pa.mu_H(2) * sum(fl.S2(:,:,t) .* repmat( X2, 1, pa.num ), 1 )'      ...
                    + pa.mu_H(3) * sum(fl.S3(:,:,t) .* repmat( X3, 1, pa.num ), 1 )'     ...
                    + pa.mu_H(4) * sum(fl.S4(:,:,t) .* repmat( X4, 1, pa.num ), 1 )'   ) ...
                    ./ ( p.w_H(:, t-1) .* Q.H(:, t)   ); 
    new.w_Lh = ( pa.mu_L(1) * sum(fl.S1(:,:,t) .* repmat( X1, 1, pa.num ), 1 )'     ...
                    + pa.mu_L(2) * sum(fl.S2(:,:,t) .* repmat( X2, 1, pa.num ), 1 )'      ...
                    + pa.mu_L(3) * sum(fl.S3(:,:,t) .* repmat( X3, 1, pa.num ), 1 )'     ...
                    + pa.mu_L(4) * sum(fl.S4(:,:,t) .* repmat( X4, 1, pa.num ), 1 )'   ) ...
                    ./ ( p.w_L(:, t-1) .* Q.L(:, t)   ); 
    new.r_h = ( pa.mu_K(1) * sum(fl.S1(:,:,t) .* repmat( X1, 1, pa.num ), 1 )'    ...
                    + pa.mu_K(2) * sum(fl.S2(:,:,t) .* repmat( X2, 1, pa.num ), 1 )'      ...
                    + pa.mu_K(3) * sum(fl.S3(:,:,t) .* repmat( X3, 1, pa.num ), 1 )'     ...
                    + pa.mu_K(4) * sum(fl.S4(:,:,t) .* repmat( X4, 1, pa.num ), 1 )'   ) ...
                    ./ ( p.r(:, t-1) .* Q.k(:, t)   ); 
end

% numeraire
numeraire = new.w_Lh(1);
new.w_Hh = new.w_Hh /numeraire;
new.w_Lh = new.w_Lh / numeraire;
new.r_h = new.r_h / numeraire;

end

